apiVersion: v1
kind: Service
metadata:
  labels:
    app: cardme
  name: cardme
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cardme
  type: LoadBalancer
status:
  loadBalancer: {}
