default:

setup:
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
	. ~/.nvm/nvm.sh
	nvm install v17.6.0
  wget https://golang.org/dl/go1.19.3.linux-amd64.tar.gz
	export PATH="/usr/local/go/bin:$PATH"
	sudo yum install git
	git clone https://github.com/chihiro-yabuta/cardme.git