version: '3'
services:
  git:
    build:
      context: .
      dockerfile: '.k8s/docker/git/Dockerfile'
    container_name: cardme_git
    tty: true
    restart: always
    volumes:
      - ./:/root/cardme
    working_dir: /root/cardme
  client:
    image: node
    container_name: cardme_client
    tty: true
    restart: always
    volumes:
      - ./:/root/cardme
    working_dir: /root/cardme/client
  server:
    build:
      context: .
      dockerfile: '.k8s/docker/server/Dockerfile'
    container_name: cardme_server
    tty: true
    restart: always
    volumes:
      - ./:/root/cardme
      - ./server/redis.conf:/usr/local/etc/redis/redis.conf
    working_dir: /root/cardme/server
    command: redis-server /usr/local/etc/redis/redis.conf
