version: '3'
services:
  app:
    build:
      context: .
      dockerfile: 'Dockerfile'
    container_name: 'cardme'
    tty: true
    restart: always
    volumes:
      - ./:/root/cardme
    working_dir: '/root/cardme'