services:
  cardme:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        git_email: ${git_email}
        git_name: ${git_name}
    container_name: cardme
    volumes:
      - ./:/cardme
    working_dir: /cardme
    tty: true
    restart: always