version: 2

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Echo Test
          command: echo "CircleCI Test"
  deploy:
    docker:
      image: chihiro1129yabuta/cardme:opt
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${KEY_FINGERPRINT}"
      - run: aws configure set aws_access_key_id ${access}
      - run: aws configure set aws_secret_access_key ${secret}
      - run: aws configure set region ap-northeast-1
      - run: eksctl utils write-kubeconfig --cluster=cardme-cluster
      - run: kubectl rollout restart deployment cardme

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
