
version: 2

jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        docker:
            image: cimg/base:current
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - "${KEY_FINGERPRINT}"
            - run: ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} "${RUN}"

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: dev-server