apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cardme
  name: cardme
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cardme
  strategy: {}
  template:
    metadata:
      labels:
        app: cardme
    spec:
      volumes:
      - name: vol
        emptyDir: {}
      initContainers:
      - name: git
        image: bitnami/git
        command:
          - git
          - clone
          - https://github.com/chihiro-yabuta/cardme.git
          - cardme
        volumeMounts:
          - name: vol
            mountPath: cardme
      containers:
      - args:
        - make
        - c
        image: node
        name: client
        volumeMounts:
          - name: vol
            mountPath: cardme
        tty: true
        resources: {}
        workingDir: /cardme
      - args:
        - make
        - s
        image: chihiro1129yabuta/cardme:server
        name: server
        volumeMounts:
          - name: vol
            mountPath: cardme
        tty: true
        ports:
        - containerPort: 8080
        resources: {}
        workingDir: /cardme
status: {}
